### ISSUE TITLE
Crash using score function in BCE

### ISSUE THREAD

**Issue by HEmile** [HEmile/storchastic#48]
After training for a while, some methods (at least ScoreFunction with no baseline and LAX) on the normal vae will crash using:

```
/opt/conda/conda-bld/pytorch_1579040055865/work/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [11,0,0], thread: [447,0,0] Assertion `*input >= 0. && *input <= 1.` failed.

Traceback (most recent call last):
  File "examples/vae/normal_vae.py", line 44, in <module>
    main(NormalVAE)
  File "/home/ekn274/storchastic/examples/vae/train.py", line 200, in main
    train_loss = train(epoch, model, train_loader, device, optimizer, args, writer)
  File "/home/ekn274/storchastic/examples/vae/train.py", line 32, in train
    storch.add_cost(loss_function(recon_batch, data), "reconstruction")
  File "/home/ekn274/storchastic/examples/vae/train.py", line 17, in loss_function
    bce = storch.nn.b_binary_cross_entropy(recon_x, x, reduction="sum")
  File "/home/ekn274/storchastic/storch/wrappers.py", line 191, in wrapper
    outputs = fn(*args, **kwargs)
  File "/home/ekn274/storchastic/storch/nn/losses.py", line 50, in b_binary_cross_entropy
    return storch.sum(unreduced, indices)
  File "/home/ekn274/storchastic/storch/storch.py", line 39, in sum
    return storch.reduce(torch.sum, plates=reduced_batches)(tensor, indices)
  File "/home/ekn274/storchastic/storch/wrappers.py", line 191, in wrapper
    outputs = fn(*args, **kwargs)
  File "/home/ekn274/storchastic/storch/wrappers.py", line 184, in wrapper
    return fn(*args, **kwargs)
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by HEmile** [comment]
Seems like the BCE loss gets invalid inputs because some numbers go wrong. Is it NaNs or just rounding errors?
